In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/drw-crypto-market-prediction/sample_submission.csv
/kaggle/input/drw-crypto-market-prediction/train.parquet
/kaggle/input/drw-crypto-market-prediction/test.parquet

In [2]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, median_absolute_error, r2_score
from scipy.stats import pearsonr, spearmanr
import polars as pl
import numpy as np
from tqdm import tqdm
from datetime import datetime

# 1 Data

In [3]:
data = pl.read_parquet(
    "/kaggle/input/drw-crypto-market-prediction/train.parquet"
).sort("timestamp", descending = False)

def add_features(df: pl.DataFrame):
    df = df.with_columns([
        (pl.col("buy_qty") - pl.col("sell_qty")).alias("buysell_delta"),
    ])
    return df

data = add_features(data)
data

shape: (525_887, 898)
┌─────────┬─────────┬─────────┬──────────┬───┬──────────┬──────────┬───────────────┬───────────────┐
│ bid_qty ┆ ask_qty ┆ buy_qty ┆ sell_qty ┆ … ┆ X890     ┆ label    ┆ timestamp     ┆ buysell_delta │
│ ---     ┆ ---     ┆ ---     ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---           ┆ ---           │
│ f64     ┆ f64     ┆ f64     ┆ f64      ┆   ┆ f64      ┆ f64      ┆ datetime[ns]  ┆ f64           │
╞═════════╪═════════╪═════════╪══════════╪═══╪══════════╪══════════╪═══════════════╪═══════════════╡
│ 15.283  ┆ 8.425   ┆ 176.405 ┆ 44.984   ┆ … ┆ 0.530636 ┆ 0.562539 ┆ 2023-03-01    ┆ 131.421       │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 00:00:00      ┆               │
│ 38.59   ┆ 2.336   ┆ 525.846 ┆ 321.95   ┆ … ┆ 0.530269 ┆ 0.533686 ┆ 2023-03-01    ┆ 203.896       │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 00:01:00      ┆               │
│ 0.442   ┆ 60.25   ┆ 159.227 ┆ 136.369  ┆ … ┆ 0.529901 ┆ 0.546505 ┆ 2023-03-01    ┆ 22.858        │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 00:02:00      ┆               │
│ 4.865   ┆ 21.016  ┆ 335.742 ┆ 124.963  ┆ … ┆ 0.529534 ┆ 0.357703 ┆ 2023-03-01    ┆ 210.779       │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 00:03:00      ┆               │
│ 27.158  ┆ 3.451   ┆ 98.411  ┆ 44.407   ┆ … ┆ 0.529167 ┆ 0.362452 ┆ 2023-03-01    ┆ 54.004        │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 00:04:00      ┆               │
│ …       ┆ …       ┆ …       ┆ …        ┆ … ┆ …        ┆ …        ┆ …             ┆ …             │
│ 4.163   ┆ 6.805   ┆ 39.037  ┆ 55.351   ┆ … ┆ 0.243172 ┆ 0.396289 ┆ 2024-02-29    ┆ -16.314       │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 23:55:00      ┆               │
│ 2.29    ┆ 4.058   ┆ 110.201 ┆ 67.171   ┆ … ┆ 0.243004 ┆ 0.328993 ┆ 2024-02-29    ┆ 43.03         │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 23:56:00      ┆               │
│ 5.237   ┆ 3.64    ┆ 70.499  ┆ 30.753   ┆ … ┆ 0.242836 ┆ 0.189909 ┆ 2024-02-29    ┆ 39.746        │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 23:57:00      ┆               │
│ 5.731   ┆ 4.901   ┆ 22.365  ┆ 52.195   ┆ … ┆ 0.242668 ┆ 0.410831 ┆ 2024-02-29    ┆ -29.83        │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 23:58:00      ┆               │
│ 3.925   ┆ 3.865   ┆ 86.585  ┆ 217.137  ┆ … ┆ 0.242501 ┆ 0.731542 ┆ 2024-02-29    ┆ -130.552      │
│         ┆         ┆         ┆          ┆   ┆          ┆          ┆ 23:59:00      ┆               │
└─────────┴─────────┴─────────┴──────────┴───┴──────────┴──────────┴───────────────┴───────────────┘

# 2 Pre-Processing / Feature Engineering

In [4]:
start = datetime(2023, 3, 1, 0, 0)
end   = datetime(2024, 2, 29, 23, 59, 59)

# v1
# features = ['X35', 'X96', 'X113', 'X126', 'X261', 'X539', 'X666', 'X690', 'X696']
## v2: 160625 : scor >= 65
features = ['X610',
 'X853',
 'X21',
 'X239',
 'X246',
 'X854',
 'X20',
 'X219',
 'X572',
 'X860',
 'X863',
 'buysell_delta',
 'X300',
 'X301']

X_train = data.filter(
    (pl.col("timestamp") >= pl.lit(start)) & (pl.col("timestamp") <= pl.lit(end))
).select(features)

y_train = data.filter(
    (pl.col("timestamp") >= pl.lit(start)) & (pl.col("timestamp") <= pl.lit(end))
)["label"]

X_train_np = X_train.to_numpy()
y_train_np = y_train.to_numpy()

X_train

shape: (525_887, 14)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ X610      ┆ X853      ┆ X21      ┆ X239      ┆ … ┆ X863      ┆ buysell_d ┆ X300      ┆ X301      │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ elta      ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64      ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│           ┆           ┆          ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.433492  ┆ 1.9140625 ┆ 0.816321 ┆ -0.118683 ┆ … ┆ 0.21857   ┆ 131.421   ┆ -0.426144 ┆ -0.429667 │
│ 1.433492  ┆ 1.914019  ┆ 0.674792 ┆ -0.165429 ┆ … ┆ 0.088014  ┆ 203.896   ┆ -0.424388 ┆ -0.427677 │
│ 1.398892  ┆ 1.913976  ┆ 0.610116 ┆ -0.163062 ┆ … ┆ -0.147363 ┆ 22.858    ┆ -0.429804 ┆ -0.433164 │
│ 1.391091  ┆ 1.913932  ┆ 0.618529 ┆ -0.386082 ┆ … ┆ -0.09459  ┆ 210.779   ┆ -0.417753 ┆ -0.420918 │
│ 1.341363  ┆ 1.913889  ┆ 0.623192 ┆ -0.382072 ┆ … ┆ 0.162221  ┆ 54.004    ┆ -0.413584 ┆ -0.416712 │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ -1.741225 ┆ 1.72678   ┆ 0.772499 ┆ 0.157325  ┆ … ┆ 0.636555  ┆ -16.314   ┆ -1.400662 ┆ -1.568378 │
│ -1.734718 ┆ 1.726736  ┆ 0.818153 ┆ 0.046492  ┆ … ┆ 0.649406  ┆ 43.03     ┆ -1.392645 ┆ -1.554896 │
│ -1.729189 ┆ 1.726693  ┆ 0.191078 ┆ -0.153582 ┆ … ┆ 0.535593  ┆ 39.746    ┆ -1.380596 ┆ -1.531802 │
│ -1.696274 ┆ 1.726649  ┆ 0.794395 ┆ 0.133209  ┆ … ┆ 0.647059  ┆ -29.83    ┆ -1.389023 ┆ -1.555196 │
│ -1.77287  ┆ 1.726606  ┆ 1.433281 ┆ 0.536388  ┆ … ┆ 0.331538  ┆ -130.552  ┆ -1.394165 ┆ -1.588371 │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
y_train

shape: (525_887,)
Series: 'label' [f64]
[
	0.562539
	0.533686
	0.546505
	0.357703
	0.362452
	…
	0.396289
	0.328993
	0.189909
	0.410831
	0.731542
]

# 3 Model

In [6]:
# from xgboost import XGBRegressor

# # XGBoost (GPU)
# model = XGBRegressor(
#     booster="gbtree",
#     tree_method="gpu_hist",
#     predictor="gpu_predictor",
#     n_estimators=10000,        # very large number of trees
#     learning_rate=0.005,       # very small step size
#     max_depth=12,              # deep trees to capture complex interactions
#     min_child_weight=1,        # allow splits on small partitions
#     gamma=0,                   # no minimum loss reduction
#     subsample=1.0,             # use all rows
#     colsample_bytree=1.0,      # use all columns
#     reg_alpha=0,               # no L1 regularization
#     reg_lambda=1,              # modest L2 regularization
#     random_state=42,
#     verbosity=0,
#     n_jobs=-1
# )

from lightgbm import LGBMRegressor

model = LGBMRegressor(
    device = 'gpu',
    boosting_type="gbdt",
    n_estimators=10000,        # as in XGBoost
    learning_rate=0.005,       # small step size
    max_depth=12,              # limit tree depth (optional; LightGBM also uses num_leaves)
    num_leaves=2**12 - 1,      # roughly 4095 leaves for depth=12
    min_child_samples=1,       # minimum data in one leaf (≈ min_child_weight)
    subsample=1.0,             # bagging fraction (rows)
    subsample_freq=1,          # bagging frequency; 1 means every iteration
    feature_fraction=1.0,      # feature fraction per tree
    reg_alpha=0.0,             # L1 regularisation
    reg_lambda=1.0,            # L2 regularisation
    random_state=42,
    verbosity=-1,
    n_jobs=-1
)

model.fit(X_train_np, y_train_np)

1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.

LGBMRegressor(device='gpu', feature_fraction=1.0, learning_rate=0.005,
              max_depth=12, min_child_samples=1, n_estimators=10000, n_jobs=-1,
              num_leaves=4095, random_state=42, reg_lambda=1.0,
              subsample_freq=1, verbosity=-1)

# 4 Prediction

## 4.1 Preprocess Test

In [7]:
test = pl.read_parquet("/kaggle/input/drw-crypto-market-prediction/test.parquet")
test = test.with_row_index("ID", offset=1)
test = add_features(test)

X_test = test.select(features)
X_test

shape: (538_150, 14)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ X610      ┆ X853     ┆ X21       ┆ X239      ┆ … ┆ X863      ┆ buysell_d ┆ X300      ┆ X301      │
│ ---       ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ elta      ┆ ---       ┆ ---       │
│ f64       ┆ f64      ┆ f64       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.022706  ┆ 1.662674 ┆ -0.041204 ┆ -0.008246 ┆ … ┆ -0.270279 ┆ -0.384    ┆ -0.622242 ┆ -0.517398 │
│ -0.195151 ┆ 0.638845 ┆ -0.227728 ┆ -0.011749 ┆ … ┆ -0.356306 ┆ 123.937   ┆ 0.266341  ┆ 0.168849  │
│ -0.075595 ┆ 1.521962 ┆ 0.060063  ┆ 0.085643  ┆ … ┆ 0.268433  ┆ -33.781   ┆ -0.459381 ┆ -0.458948 │
│ 0.837502  ┆ 1.609115 ┆ -0.021846 ┆ -0.100523 ┆ … ┆ -0.364048 ┆ 103.436   ┆ -0.714608 ┆ -0.983835 │
│ 0.12267   ┆ 1.162847 ┆ -0.064359 ┆ 0.056144  ┆ … ┆ 0.184046  ┆ -6.036    ┆ -0.090277 ┆ -0.005034 │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ -1.498386 ┆ 0.546181 ┆ 0.696552  ┆ 0.54927   ┆ … ┆ -0.064651 ┆ 31.879    ┆ -0.820639 ┆ -0.886356 │
│ 0.019754  ┆ 0.240017 ┆ -0.021502 ┆ -0.065665 ┆ … ┆ 0.186569  ┆ 25.906    ┆ -1.207428 ┆ -1.212013 │
│ -0.863551 ┆ 0.724219 ┆ 0.057377  ┆ 0.142522  ┆ … ┆ 0.007022  ┆ -14.357   ┆ -0.370657 ┆ -0.344779 │
│ -0.738579 ┆ 0.065885 ┆ -0.61089  ┆ -0.077488 ┆ … ┆ 0.164258  ┆ -60.237   ┆ 0.203799  ┆ 0.183172  │
│ 0.18635   ┆ 1.677257 ┆ 1.598489  ┆ 0.4177    ┆ … ┆ -0.049451 ┆ -11.016   ┆ 0.564667  ┆ 0.47623   │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## 4.2 Predict

In [8]:
y_pred = model.predict(X_test.to_numpy())
submission = pl.DataFrame({
    "ID": test["ID"],
    "prediction": y_pred
})
submission

shape: (538_150, 2)
┌────────┬────────────┐
│ ID     ┆ prediction │
│ ---    ┆ ---        │
│ u32    ┆ f64        │
╞════════╪════════════╡
│ 1      ┆ -0.440642  │
│ 2      ┆ -0.578727  │
│ 3      ┆ -0.108385  │
│ 4      ┆ -0.663513  │
│ 5      ┆ 0.133712   │
│ …      ┆ …          │
│ 538146 ┆ -0.527572  │
│ 538147 ┆ -2.705031  │
│ 538148 ┆ 0.043969   │
│ 538149 ┆ 0.316666   │
│ 538150 ┆ 1.396375   │
└────────┴────────────┘

## 5 Submission

In [9]:
submission.write_csv("/kaggle/working/submission.csv")